### ISSUE TITLE
server.cfg

### ISSUE THREAD

**Issue by Krenair** [Azelphur-Servers/TF2#12] opened 2015-07-10 02:05 UTC
Another important file we should deal with in this repository is our equivalent of tf2/tf/cfg/server.cfg
I know that we currently use tf/cfg/surf/server.cfg etc.
We should `exec sensitiveinfo.cfg` or something to include sensitive data like rcon_password or tf_server_identity_token. Dunno about tf_server_identity_account_id.

**Comment by RobAWarner** [comment] 2015-07-13 21:18
~~Another issue I noticed with the server cfg is that it gets added to 'cfg/sourcemod' instead of just 'cfg/'.~~

(Caused by incorrect config in surf.yaml, now fixed)

**Comment by Azelphur** [comment] 2015-08-03 14:02
Fixed in e274d6a ... why did we need an issue for this xD

**Closed as completed by Azelphur** 2015-08-03 14:02 UTC

**Comment by Krenair** [comment] 2015-08-03 14:15
I think I just turned all entries in our list into issues.
